version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./assets:/usr/share/nginx/html/assets:ro
    restart: always
